### ISSUE TITLE
with 16gb of vram and 128gb of ram = OOm Error

### ISSUE THREAD

**Issue by TheMich01** [6Morpheus6/bagel#1]
I beleive that the minimum requirement is not 12gb of vram, i have 16gb of vram and 128gb of ram, but:

torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 130.00 MiB. GPU 0 has a total capacity of 15.70 GiB of which 75.56 MiB is free. Process 3233 has 288.45 MiB memory in use. Including non-PyTorch memory, this process has 15.33 GiB memory in use. Of the allocated memory 15.08 GiB is allocated by PyTorch, and 133.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

so i think than 24 gb of vram is  the minimum required to run bagel.
anyway: thanks for the script.
bye

**Comment by 6Morpheus6** [comment]
@TheMich01 I just saw your issue. No clue why I didn't get notified, notifications are enabled.
I came across to fix a download error related to the latest huggingface_hub update and tested the app.
Since I use an RTX 5080 with 16GB VRAM, I can only guess the requirements, but it should work on 12GB VRAM.
Overall Bagel needs 25GB memory. Due to CUDA System Fallback Policy it can use shared GPU memory, which is always half of the RAM. With 12GB VRAM and 32GB VRAM there should be 3GB shared memory left, so theoretically it should work.

The only reason I can imagine why it fails for you is that CUDA System Fallback Policy is disabled.
Make sure to use current NVIDIA drivers, open Nvidia System control - 3D settings and
set **CUDA System Fallback Policy** to _**Prefer System Fallback**_ or _**Driver Default**_, if it isn't set that way.

<img width="865" height="815" alt="Image" src="https://github.com/user-attachments/assets/1bf2c39b-21c5-4775-b4ce-00aaa0c9d145" />
___

Here are my test result (16GB VRAM / 64GB RAM):
- During the generation
<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/0e582873-6299-424d-86f6-ce2e5403577c" />

- After the generation

<img width="3840" height="2148" alt="Image" src="https://github.com/user-attachments/assets/cd884ca1-4780-4185-a123-f2463bd2c324" />

If you want to use Bagel you could try Bagel-Dfloat11. It uses around 25% less memory than Bagel.

**Comment by TheMich01** [comment]
Thanks for your answer, i solved the problem, now i have a 3090 and i have no problem al all, i beleive the 4060Ti 16gb on my ubuntu use different drivers than windows, and nvidia on ubuntu has some problems.... sometimes impossible to solve.

**Comment by 6Morpheus6** [comment]
@TheMich01 Ahh, this explains it. On Linux there is no cuda system memory fallback sadly. And as soon as your GPU gets at the limit, you get an OOM.
If you are using Comfyui, you can also try Flux-Kontext. It's better than Bagel. With a 3090 the stand alone Flux-Kontext app might work too. With less than 24GB VRAM it's simply too slow. But Comfyui would be way faster. Another option is Qwen Image Edit.
Also available in Comfyui or Wan2GP.
But I'm glad we could sort it out and everything is working for you now. :)
